version: 0.2

phases:
  build:
    commands:
      - # Build command 1
      - # Build command 2
      - # ...

artifacts:
  files:
    - build/**/*
    - yarn.lock
    - package.json
    - # ... any other output files
